import { Icon } from "@/components/ui/icons";
import { requireAdmin } from "@/features/admin/guard";
import { adminListBadges } from "@/features/admin/queries";
import { AdminBadgeForm } from "@/features/admin/admin-badge-form";

export const dynamic = "force-dynamic";

export default async function AdminBadgesPage() {
  await requireAdmin("/admin/badges");
  const badges = await adminListBadges();
  return <div className="space-y-xl"><header><p className="eyebrow text-sport-lime-deep">Reward system</p><h1 className="mt-md font-display text-5xl uppercase leading-none tablet-narrow:text-6xl">Badge &amp; pencapaian</h1><p className="mt-md max-w-2xl text-sm leading-relaxed text-mute">Bangun motivasi pengguna dengan penghargaan yang jelas dan XP yang seimbang.</p></header><div className="grid gap-md desktop:grid-cols-[minmax(0,0.9fr)_minmax(420px,1.1fr)] desktop:items-start"><section className="overflow-hidden rounded-sm border border-black/[0.08] bg-white"><div className="flex items-center justify-between border-b border-black/[0.08] p-lg"><div><p className="font-semibold">Badge tersedia</p><p className="mt-xs text-xs text-mute">{badges.filter((badge) => badge.is_active).length} sedang aktif</p></div><span className="rounded-full bg-sport-lime px-md py-sm text-xs font-semibold">{badges.length}</span></div><div className="divide-y divide-black/[0.08]">{badges.map((badge) => <article key={badge.id} className="flex items-center gap-md p-lg"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-sport-black text-sport-lime"><Icon name="target" className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-sm"><p className="font-semibold">{badge.name}</p><span className={`h-2 w-2 rounded-full ${badge.is_active ? "bg-success-bright" : "bg-stone"}`} /></div><p className="mt-xs truncate text-xs text-mute">{badge.code} · +{badge.xp_reward} XP</p></div></article>)}{badges.length === 0 && <p className="p-xl text-center text-sm text-mute">Belum ada badge.</p>}</div></section><section className="rounded-sm border border-black/[0.08] bg-white p-lg tablet-narrow:p-xl"><div className="mb-xl flex items-center gap-md border-b border-black/[0.08] pb-lg"><span className="grid h-11 w-11 place-items-center rounded-full bg-sport-lime"><Icon name="target" className="h-5 w-5" /></span><div><p className="font-semibold">Buat badge baru</p><p className="mt-xs text-xs text-mute">Tentukan kriteria dan hadiah XP.</p></div></div><AdminBadgeForm /></section></div></div>;
}
