import { Icon } from "@/components/ui/icons";
import { requireAdmin } from "@/features/admin/guard";
import { adminListChallenges } from "@/features/admin/queries";
import { AdminChallengeForm } from "@/features/admin/admin-challenge-form";

export const dynamic = "force-dynamic";

function fmt(iso: string) { return new Date(iso).toLocaleDateString("id-ID", { day: "2-digit", month: "short", year: "numeric", timeZone: "Asia/Jakarta" }); }

export default async function AdminChallengesPage() {
  await requireAdmin("/admin/challenges");
  const challenges = await adminListChallenges();
  return <div className="space-y-xl"><header><p className="eyebrow text-sport-lime-deep">Engagement program</p><h1 className="mt-md font-display text-5xl uppercase leading-none tablet-narrow:text-6xl">Challenge</h1><p className="mt-md max-w-2xl text-sm leading-relaxed text-mute">Rancang target harian dan mingguan untuk menjaga konsistensi komunitas.</p></header><div className="grid gap-md desktop:grid-cols-[minmax(0,0.9fr)_minmax(420px,1.1fr)] desktop:items-start"><section className="overflow-hidden rounded-sm border border-black/[0.08] bg-white"><div className="flex items-center justify-between border-b border-black/[0.08] p-lg"><div><p className="font-semibold">Program challenge</p><p className="mt-xs text-xs text-mute">{challenges.filter((challenge) => challenge.is_active).length} sedang aktif</p></div><span className="rounded-full bg-sport-lime px-md py-sm text-xs font-semibold">{challenges.length}</span></div><div className="divide-y divide-black/[0.08]">{challenges.map((challenge) => <article key={challenge.id} className="flex items-start gap-md p-lg"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-sport-black text-sport-lime"><Icon name="bolt" className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-sm"><p className="font-semibold">{challenge.title}</p><span className={`h-2 w-2 rounded-full ${challenge.is_active ? "bg-success-bright" : "bg-stone"}`} /></div><p className="mt-xs text-xs leading-relaxed text-mute">{challenge.period} · {fmt(challenge.starts_at)}–{fmt(challenge.ends_at)} · +{challenge.xp_reward} XP</p></div></article>)}{challenges.length === 0 && <p className="p-xl text-center text-sm text-mute">Belum ada challenge.</p>}</div></section><section className="rounded-sm border border-black/[0.08] bg-white p-lg tablet-narrow:p-xl"><div className="mb-xl flex items-center gap-md border-b border-black/[0.08] pb-lg"><span className="grid h-11 w-11 place-items-center rounded-full bg-sport-lime"><Icon name="bolt" className="h-5 w-5" /></span><div><p className="font-semibold">Buat challenge baru</p><p className="mt-xs text-xs text-mute">Tentukan periode, target, dan hadiah.</p></div></div><AdminChallengeForm /></section></div></div>;
}
